name: KpWorlflow

on:
  workflow_dispatch:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - run: mvn compile

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - run: mvn clean test

