name: KpWorlflow

on:
  workflow_dispatch:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - uses: actions/checkout@v7
      - run: mvn build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - uses: actions/checkout@v7
      - run: mvn clean test

